### ISSUE TITLE
No function "function" error

### ISSUE THREAD

**Issue by standage** [oyvble/euroformix#1]
Greetings!

I am running EuroForMix 2.2.1 using the ENFSI data posted on the website. I have no problem importing the data and configuring the model, but when I attempt to run the Quantitative LR I get the following message on the console.

> Error in function(x) dbeta(x, 1, 1) : could not find function "function"

The `dbeta(x, 1, 1)` looks like a parameter for the stutter model. I have the stutter model turned off, so I'm wondering why this message is popping up. Please advise.

In case it helps, I'm running R 3.6.1, and I was able to reproduce this error on Mac OS X "Mojave" as well as Ubuntu 18.04. Thanks!

**Comment by oyvble** [comment]
Hi Daniel, there is unfortunately a bug in the new version. Please use the previous one.
Best regards Øyvind


Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by oyvble** [comment]
I have updated the v2.2.1 version now. You can try reinstall it. The dbeta function is a prior distribution for the stutterprop paramerer, its always stored in settings. The bug happened because i used wrong argument in creating environment object.
Best regards Øyvind

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by standage** [comment]
Confirmed. I installed the latest master using devtools::install_github and the error has gone away. Thanks for your rapid response!
